---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maeregqx/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - export COMPOSER_ALLOW_SUPERUSER=1
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan db:seed
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
